version: "3.8"
services:

  subscription_redis:
    image: redis:latest
    container_name: subscription_redis
    ports:
      - "6379:6379"
    networks:
      - subscription_network

  subscription_server:
    platform: linux/amd64
    container_name: subscription_server
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "cargo watch -x fmt -s 'mold -run cargo run'"
    volumes:
      - .:/app
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target:/app/target
    environment:
      RUST_LOG: "actix_web=info"
      REDIS_URL: "redis://subscription_redis:6379"
      ADDRESS: 0.0.0.0
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - subscription_redis
    networks:
      - subscription_network

networks:
  subscription_network:

volumes:
  cargo-registry:
  cargo-git:
  target: