services:

  artizans_redis:
    image: redis:latest
    container_name: artizans_redis
    ports:
      - "6379:6379"
    networks:
      - artizans_network

  artizans_webserver:
    platform: linux/amd64
    container_name: artizans_webserver
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "cargo watch -x fmt -s 'mold -run cargo run'"
    volumes:
      - .:/app
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target:/app/target
    environment:
      RUST_LOG: "actix_web=info"
      REDIS_URL: "redis://artizans_redis:6379"
      ADDRESS: 0.0.0.0
      PORT: 8080
      ENVIRONMENT: "development"
    ports:
      - "8080:8080"
    depends_on:
      - artizans_redis
    networks:
      - artizans_network

networks:
  artizans_network:

volumes:
  cargo-registry:
  cargo-git:
  target: